### ISSUE TITLE
The NestedVirt=$true Statement doesn't work

### ISSUE THREAD

**Issue by andregebel** [DellGEOS/AzureStackHOLs#49] opened 2023-11-23 09:44 UTC
Issues after deploy Azure Stack VMs in nested virtualization.

If the Hyper-V role can not be installed in WIndows Admin Center Wizard , shutdown the Azure Stack VMs an open an Powershell "Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true"  for both VMs an ry again. It should work.

https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/01-DeployAzureStackHCICluster-WAC#labconfig
Labconfig

**Comment by Karl-WE** [comment] 2024-01-10 20:52
had the same weird experience @jaromirk remember our slack discussion recently. Azure Stack 23H2 OS and your deployment config was affected, quite weird as there were no code changes from your side. using WAC to enable nested virt., everything was fine.

I first thought this was because a quirk using the 2311 New Gen WAC deployment wizard but I believe @andregebel hasn't used it, did you?

**Comment by jaromirk** [comment] 2024-01-12 08:07
That what's script is doing. ExposeVirtualizationExtensions. WAC will never install it in VMs. you need to use DISM commands to install Hyper-V

**Comment by jaromirk** [comment] 2024-01-12 08:09
https://github.com/microsoft/MSLab/blob/master/Scripts/3_Deploy.ps1#L633-L638

You need to do "Step 5" here:
https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/01-DeployAzureStackHCICluster-WAC#get-started-tab

**Comment by Karl-WE** [comment] 2024-05-04 11:38
@jaromirk also believe this could be closed as it is a PS code regression in of WAC how they handle nested virtualization.
Here's the WAC feedback item: https://feedback.azure.com/d365community/idea/a9268101-e0ac-ee11-92bc-000d3ae54955

**Closed** 2024-09-24 10:52 UTC
